#
# Makefile for the Linux/SuperH CPU-specifc IRQ handlers.
#
obj-$(CONFIG_SUPERH32)			+= imask.o
obj-$(CONFIG_CPU_SH5)			+= intc-sh5.o
obj-$(CONFIG_CPU_HAS_IPR_IRQ)		+= ipr.o
obj-$(CONFIG_CPU_SUBTYPE_FLI7510)	+= ilc3.o
obj-$(CONFIG_CPU_SUBTYPE_STX5197)	+= ilc3.o
obj-$(CONFIG_CPU_SUBTYPE_STX5206)	+= ilc3.o
obj-$(CONFIG_CPU_SUBTYPE_STX7100)	+= ilc3_stx7100.o
obj-$(CONFIG_CPU_SUBTYPE_STX7105)	+= ilc3.o
obj-$(CONFIG_CPU_SUBTYPE_STX7108)	+= ilc3.o
obj-$(CONFIG_CPU_SUBTYPE_STX7111)	+= ilc3.o
obj-$(CONFIG_CPU_SUBTYPE_STX7141)	+= ilc3.o
obj-$(CONFIG_CPU_SUBTYPE_STX7200)	+= ilc3.o
