/*
 * include/asm-sh/irl.h
 *
 * Copyright (c) STMicroelectronics 2007
 *
 * IRL interrupt lines
 */

#ifndef _ASM_SH_IRL_H
#define _ASM_SH_IRL_H

/*
 * Interrupts which are generated by IRL lines when in individual interrupt
 * mode. See plat_irq_setup_pins().
 */
#define IRL0_IRQ	2
#define IRL1_IRQ	5
#define IRL2_IRQ	8
#define IRL3_IRQ	11

#endif /* _ASM_SH_IRL_H */
