#
# Makefile for STMicroelectronics boards common implementation
#

obj-$(CONFIG_SH_ST_HARP_IRQ) += harp-irq.o
obj-$(CONFIG_SH_ST_EPLD) += epld.o

obj-$(CONFIG_SH_ST_DB641) += db641.o
obj-$(CONFIG_SH_ST_DB679) += db679.o
obj-$(CONFIG_SH_ST_MB520) += mb520.o
obj-$(CONFIG_SH_ST_MB562) += mb562.o
obj-$(CONFIG_SH_ST_MB588) += mb588.o
obj-$(CONFIG_SH_ST_MB705) += mb705.o
obj-$(CONFIG_SH_ST_MB705_AUDIO) += mb705-audio.o
obj-$(CONFIG_SH_ST_MB705_DISPLAY) += mb705-display.o
obj-$(CONFIG_SH_ST_MB705_FPBUTTON) += mb705-fpbutton.o
