#!/bin/sh

test -r /etc/sysconfig/config && . /etc/sysconfig/config

if test "$IPV4" = "dhcp"; then
  exec /sbin/udhcpc -f -S -p /tmp/udhcpc.pid -s /etc/init.d/dhcpc-event
else
  ifconfig eth0 $IPV4 netmask $IPV4_NETMASK broadcast $IPV4_BROADCAST
  route add default gw $IPV4_GATEWAY
fi

if test -r /etc/sysconfig/resolv.conf; then
  ln -s sysconfig/resolv.conf /etc/resolv.conf
fi
