#!/bin/sh

MINISATIP_PROGRAM=minisatip
MINISATIP5_PROGRAM=minisatip5
MINISATIP7_PROGRAM=minisatip7
MINISATIP8_PROGRAM=minisatip8
test -r /etc/sysconfig/config && . /etc/sysconfig/config

if test "$MINISATIP" != "yes" -a "$MINISATIP5" != "yes" -a "$MINISATIP7" != "yes" -a "$MINISATIP8" != "yes"; then
  exit 0
fi

. /etc/init.d/axe-settings

# renice kernel demuxers
if test "$DEMUXERS_RENICE" = "yes"; then
  a=""
  for i in $(ps -o pid,nice,comm | grep "kdmxts_64" | cut -d 'k' -f 1); do
    if test "$i" -gt 15; then a="$a $i"; fi
  done
  renice -15 $a
fi

cd /tmp
while test ! -f /tmp/nosatip; do
  while ! test -r /tmp/satip-network; do
    nc -l 127.0.0.1:999 -e /etc/init.d/satip-network
  done
  MINISATIP_PROGRAM=minisatip
  MINISATIP5_PROGRAM=minisatip5
  MINISATIP7_PROGRAM=minisatip7
  MINISATIP8_PROGRAM=minisatip8
  . /etc/sysconfig/config
  if test "$MINISATIP" = "yes"; then
    nice -5 $MINISATIP_PROGRAM -f -g $MINISATIP_OPTS
    logger -p local0.notice "minisatip exited $?, restarting"
  elif test "$MINISATIP5" = "yes"; then
    nice -5 $MINISATIP5_PROGRAM -f -g $MINISATIP5_OPTS
    logger -p local0.notice "minisatip5 exited $?, restarting"
  elif test "$MINISATIP7" = "yes"; then
    nice -5 $MINISATIP7_PROGRAM -f -g $MINISATIP7_OPTS
    logger -p local0.notice "minisatip7 exited $?, restarting"
  elif test "$MINISATIP8" = "yes"; then
    nice -5 $MINISATIP8_PROGRAM -f -g $MINISATIP8_OPTS
    logger -p local0.notice "minisatip8 exited $?, restarting"
  else
    exit 0
  fi
  if test -f /tmp/nosatip; then
    sleep 87323123
  fi
done
