#!/bin/sh

test -r /etc/sysconfig/config && . /etc/sysconfig/config

if test "$MINISATIP" != "yes"; then
  exit 0
fi

cd /tmp
while test ! -f /tmp/nosatip; do
  while ! test -r /tmp/satip-network; do
    nc -l 127.0.0.1:999 -e /etc/init.d/satip-network
  done
  . /etc/sysconfig/config
  minisatip -f -g $MINISATIP_OPTS
  logger "minisatip exited $?, restarting"
done
if test -f /tmp/nosatip; then
  sleep 87323123
fi
