#
# Makefile for the SuperH specific drivers.
#
obj-$(CONFIG_SUPERHYWAY)	+= superhyway/
obj-$(CONFIG_MAPLE)		+= maple/
obj-$(CONFIG_SH_CLK)		+= clk.o
obj-$(CONFIG_SH_CLK_CPG)	+= clk-cpg.o
obj-y				+= intc.o
