#
# Makefile for LIRC drivers
#
# Copyright (C) 2004-2009 STMicroelectronics
# Author  Angelo Castello <angelo.castello@st.com>

obj-$(CONFIG_LIRC_SUPPORT) += lirc_dev.o
obj-$(CONFIG_LIRC_MCEUSB2) += lirc_mceusb2.o
obj-$(CONFIG_LIRC_MCEUSB) += lirc_mceusb.o
obj-$(CONFIG_LIRC_SERIAL) += lirc_serial.o
obj-$(CONFIG_LIRC_SIR) += lirc_sir.o
obj-$(CONFIG_LIRC_STM) += lirc_stm.o
obj-$(CONFIG_LIRC_TTUSBIR) += lirc_ttusbir.o