#!/bin/sh

FILE="$1"
MTDDEV="/dev/mtd3"
CHECKSTR="Linux-2.6.32.42_stm24_0208-idl4k"

if test "$FILE" = "-h" -o "$FILE" = "--help" -o "$FILE" = ""; then
  echo "Usage: $0 FIRMWARE"
  exit 1
fi

echo "Preparing to flash - killing minisatip, unmounting USB sticks"
umount /media/*
touch /tmp/nosatip
killall -9 minisatip
sync ; sync

sleep 3

first=true
second=true
while test 1 -eq 1; do
  FILESIZE=$(stat -c "%s" "$FILE")
  if test -z "$FILESIZE" -o $FILESIZE -le 0; then
    echo "Unable to determine file size for $FILE"
    exit 1
  fi
  echo "Verifying... Dumping current flash contents."
  nanddump -f "$FILE.old" -l "$FILESIZE" "$MTDDEV"
  FILESIZE2=$(stat -c "%s" "$FILE.old")
  if test "$FILESIZE" -gt "$FILESIZE2"; then
    echo "Unable to verify (file sizes does not match - $FILESIZE > $FILESIZE2)"
    exit 1
  fi
  if ! dd if=/dev/null seek="$FILESIZE" bs=1 of="$FILE.old" 2> /dev/null; then
    echo "DD truncate failed"
    exit 1
  fi
  FILESIZE2=$(stat -c "%s" "$FILE.old")
  if test "$FILESIZE" != "$FILESIZE2"; then
    echo "Unable to verify (file sizes does not match - $FILESIZE != $FILESIZE2)"
    exit 1
  fi
  result=$(diff "$FILE.old" "$FILE")
  if test -z "$result"; then
    echo "Verify OK. Flash write successful."
    echo "Type 'reboot' now..."
    rm -f "$FILE" "$FILE.old"
    exit 0
  fi
  rm -f "$FILESIZE.old"
  if test "$first" != "true"; then
    echo "** Flash contents do not match. **"
    if test "$second" != "true"; then
      echo "** Flashing failed. Consider to use an USB stick to recover. **"
    fi
    echo -n "Repeat the flash write? Use 'Ctrl-C' to abort or Enter to repeat: "
    read i
    second=
  fi
  echo "Flashing..."
  nandwrite2 -p "$MTDDEV" "$FILE"
  first=
done
